const $=s=>document.querySelector(s);
let deferredInstallPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;const b=$('#installApp');if(b)b.hidden=false});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;const b=$('#installApp');if(b){b.hidden=true}});
function openAccount(){state.user?logout():authModal()}
$('#mobileAccount')?.addEventListener('click',openAccount);
$('#installApp')?.addEventListener('click',async()=>{if(!deferredInstallPrompt){alert('В Chrome установку можно выполнить через меню ⋮ → Установить FixNow.');return}deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('#installApp').hidden=true});

let state={token:localStorage.fixnowToken||'',user:null,problem:'',category:'',photoUrl:null};
async function uploadPhoto(){const f=$('#photo')?.files?.[0];if(!f)return null;if(f.size>1500000)throw Error('Фото должно быть меньше 1.5 МБ');const data=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)});return (await api('/api/uploads',{method:'POST',body:JSON.stringify({dataUrl:data})})).url}
async function api(path,opt={}){opt.headers={'Content-Type':'application/json',...(opt.headers||{})};if(state.token)opt.headers.Authorization='Bearer '+state.token;const r=await fetch(path,opt);const j=await r.json();if(!r.ok)throw Error(j.error||'Ошибка');return j}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function statusLabel(s){return ({new:'Новая',accepted:'Принята',in_progress:'В работе',done:'Завершена',cancelled:'Отменена'})[s]||s}
async function me(){if(!state.token){renderAccount();loadOrders();return}try{state.user=(await api('/api/me')).user;renderAccount();loadOrders();renderRolePanel()}catch(e){state.token='';localStorage.removeItem('fixnowToken');renderAccount();loadOrders()}}
function renderAccount(){const b=$('#account');b.textContent=state.user?`👤 ${state.user.name} • Выйти`:'Войти / Регистрация';b.onclick=()=>state.user?logout():authModal()}
function authModal(){const m=$('#modal');m.hidden=false;m.innerHTML=`<div class="modalbox"><button class="close" onclick="$('#modal').hidden=true">×</button><h2>FixNow аккаунт</h2><div class="tabs"><button id="loginTab">Войти</button><button id="regTab">Регистрация</button></div><div id="authForm"></div></div>`;showLogin();$('#loginTab').onclick=showLogin;$('#regTab').onclick=showRegister}
function showLogin(){$('#authForm').innerHTML=`<input id="aPhone" placeholder="Телефон"><input id="aPass" type="password" placeholder="Пароль"><button class="primary" id="doLogin">Войти</button>`;$('#doLogin').onclick=async()=>{try{const x=await api('/api/login',{method:'POST',body:JSON.stringify({phone:$('#aPhone').value.trim(),password:$('#aPass').value})});state.token=x.token;state.user=x.user;localStorage.fixnowToken=state.token;$('#modal').hidden=true;renderAccount();loadOrders();renderRolePanel()}catch(e){alert(e.message)}}}
function showRegister(){$('#authForm').innerHTML=`<input id="aName" placeholder="Имя"><input id="aPhone" placeholder="Телефон"><input id="aPass" type="password" placeholder="Пароль от 6 символов"><select id="aRole"><option value="client">Я клиент</option><option value="master">Я мастер</option></select><select id="aCity"><option>Калининград</option><option>Гурьевск</option><option>Зеленоградск</option><option>Светлогорск</option><option>Пионерский</option><option>Балтийск</option><option>Черняховск</option><option>Советск</option><option>Гусев</option></select><input id="aCat" placeholder="Категория мастера (если вы мастер)"><button class="primary" id="doReg">Создать аккаунт</button>`;$('#doReg').onclick=async()=>{try{const x=await api('/api/register',{method:'POST',body:JSON.stringify({name:$('#aName').value.trim(),phone:$('#aPhone').value.trim(),password:$('#aPass').value,role:$('#aRole').value,city:$('#aCity').value,category:$('#aCat').value.trim()})});state.token=x.token;state.user=x.user;localStorage.fixnowToken=state.token;$('#modal').hidden=true;renderAccount();loadOrders();renderRolePanel();alert(state.user.role==='master'?'Аккаунт мастера создан. Теперь дождитесь проверки администратора.':'Аккаунт клиента создан.')}catch(e){alert(e.message)}}}
async function logout(){await api('/api/logout',{method:'POST'}).catch(()=>{});state={token:'',user:null,problem:'',category:''};localStorage.removeItem('fixnowToken');renderAccount();loadOrders();renderRolePanel()}
$('#analyze').onclick=async()=>{const text=$('#problem').value.trim();if(text.length<5)return alert('Опишите проблему подробнее.');try{const a=await api('/api/analyze',{method:'POST',body:JSON.stringify({text})});state.problem=text;state.category=a.category;$('#analysis').hidden=false;$('#analysis').innerHTML=`<b>${a.icon} ${a.category}</b><span>${a.price}</span><p>${a.summary}</p><button class="primary" id="find">Найти мастеров →</button>`;$('#find').onclick=findMasters}catch(e){alert(e.message)}};
async function findMasters(){try{const a=await api('/api/masters?city='+encodeURIComponent($('#city').value)+'&category='+encodeURIComponent(state.category)+'&radius=30');$('#matches').hidden=false;$('#matchInfo').textContent=`${$('#city').value} • ${a.length} найдено`;$('#masters').innerHTML=a.map(m=>`<article class="master"><div class="avatar">${esc(m.name[0])}</div><h3>${esc(m.name)}</h3><p>${esc(m.category)} • ${esc(m.city)}</p><div>★ ${m.rating||'Новый профиль'} • ✓ проверен • 📍 ${m.distanceKm} км</div><hr><strong>Ориентир от 1 500 ₽</strong><button onclick='createOrder(${JSON.stringify(m).replace(/</g,'\\u003c')})'>Выбрать</button></article>`).join('')||`<div class="empty">Пока нет проверенных мастеров этой категории. Зарегистрируйтесь как мастер, чтобы подключиться.</div>`}catch(e){alert(e.message)}}
async function createOrder(m){if(!state.user){authModal();return}if(state.user.role!=='client')return alert('Заявки создаются из аккаунта клиента.');try{const photoUrl=await uploadPhoto();const q=await api('/api/requests',{method:'POST',body:JSON.stringify({problem:state.problem,city:$('#city').value,urgency:$('#urgency').value,masterId:m.id,photoUrl})});alert('Заявка создана: '+q.id);loadOrders()}catch(e){alert(e.message)}}
async function loadOrders(){const box=$('#ordersList');if(!box)return;if(!state.user){box.innerHTML='<div class="empty">Войдите в аккаунт, чтобы видеть свои заявки.</div>';return}try{const a=await api('/api/requests');box.innerHTML=a.length?a.map(q=>`<div class="order"><div><b>${esc(q.category)}</b><p>${esc(q.problem)}</p><small>${esc(q.city)} • ${new Date(q.createdAt).toLocaleString()}${q.photoUrl?' • 📷 фото приложено':''}</small></div><span class="status ${q.status}">${statusLabel(q.status)}</span><button onclick="chat('${q.id}')">Чат</button>${q.status==='done'&&state.user.role==='client'?`<button onclick="review('${q.id}')">Отзыв</button>`:''}</div>`).join(''):'<div class="empty">Заявок пока нет.</div>'}catch(e){box.innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
async function chat(id){try{const ms=await api('/api/messages?requestId='+id);const text=ms.map(x=>`${x.sender}: ${x.text}`).join('\n');const m=prompt('Чат по заявке '+id+'\n\n'+(text||'Сообщений пока нет.')+'\n\nВведите сообщение:');if(m){await api('/api/messages',{method:'POST',body:JSON.stringify({requestId:id,text:m})});chat(id)}}catch(e){alert(e.message)}}
async function review(id){const rating=prompt('Оценка 1–5','5');if(rating===null)return;const text=prompt('Короткий отзыв','Всё хорошо')||'';try{await api('/api/reviews',{method:'POST',body:JSON.stringify({requestId:id,rating:Number(rating),text})});alert('Спасибо! Отзыв сохранён.');loadOrders()}catch(e){alert(e.message)}}
function renderRolePanel(){const p=$('#rolePanel');if(!p)return;if(!state.user){p.hidden=true;p.innerHTML='';return}p.hidden=false;if(state.user.role==='master')renderMasterDashboard();else if(state.user.role==='admin')renderAdminDashboard();else{p.innerHTML=`<div class="panel"><label>КАБИНЕТ КЛИЕНТА</label><h2>Ваши заявки находятся ниже</h2><p>После принятия заявки мастером здесь появится актуальный статус.</p></div>`}}
async function renderMasterDashboard(){const p=$('#rolePanel');try{const requests=await api('/api/requests');p.innerHTML=`<div class="panel"><div class="head"><div><label>КАБИНЕТ МАСТЕРА</label><h2>Входящие и текущие заявки</h2></div><button onclick="renderMasterDashboard()">Обновить</button></div><p>${state.user.verified?'✅ Профиль проверен — вы можете принимать заявки.':'⏳ Профиль ожидает проверки администратора.'}</p><div class="masterOrders">${requests.length?requests.map(q=>`<div class="order"><div><b>${esc(q.category)} • ${esc(q.city)}</b><p>${esc(q.problem)}</p><small>Клиент: ${esc(q.clientName)} • ${esc(q.phone)} • ${esc(q.urgency)}</small></div><span class="status ${q.status}">${statusLabel(q.status)}</span><div class="actions">${q.status==='new'?`<button onclick="changeStatus('${q.id}','accepted')">Принять</button><button onclick="changeStatus('${q.id}','cancelled')">Отклонить</button>`:''}${q.status==='accepted'?`<button onclick="changeStatus('${q.id}','in_progress')">Начать работу</button>`:''}${q.status==='in_progress'?`<button onclick="changeStatus('${q.id}','done')">Завершить</button>`:''}<button onclick="chat('${q.id}')">Чат</button></div></div>`).join(''):'<div class="empty">Пока нет заявок.</div>'}</div></div>`}catch(e){p.innerHTML=`<div class="panel"><b>${esc(e.message)}</b></div>`}}
async function changeStatus(id,status){try{await api('/api/requests/'+id,{method:'PATCH',body:JSON.stringify({status})});renderMasterDashboard();loadOrders()}catch(e){alert(e.message)}}
async function renderAdminDashboard(){const p=$('#rolePanel');try{const d=await api('/api/admin');const masters=d.users.filter(x=>x.role==='master');p.innerHTML=`<div class="panel"><div class="head"><div><label>ADMIN</label><h2>Управление FixNow</h2></div><button onclick="renderAdminDashboard()">Обновить</button></div><div class="stats"><div><b>${d.users.length}</b><span>пользователей</span></div><div><b>${masters.length}</b><span>мастеров</span></div><div><b>${d.requests.length}</b><span>заявок</span></div><div><b>${d.requests.filter(x=>x.status==='new').length}</b><span>новых</span></div></div><h3>Мастера</h3><div class="masterOrders">${masters.length?masters.map(m=>`<div class="order"><div><b>${esc(m.name)}</b><p>${esc(m.category||'Категория не указана')} • ${esc(m.city)}</p><small>${esc(m.phone||'Телефон не указан')} • ${m.verified?'проверен':'не проверен'}</small></div><span>${m.verified?'🟢':'🟡'}</span><div class="actions">${m.verified?`<button onclick="verifyMaster('${m.id}',false)">Снять проверку</button>`:`<button onclick="verifyMaster('${m.id}',true)">Проверить</button>`}</div></div>`).join(''):'<div class="empty">Мастеров нет.</div>'}</div><h3>Последние заявки</h3><div class="masterOrders">${d.requests.slice(0,10).map(q=>`<div class="order"><div><b>${esc(q.category)}</b><p>${esc(q.problem)}</p><small>${esc(q.clientName)} • ${esc(q.city)}</small></div><span class="status ${q.status}">${statusLabel(q.status)}</span></div>`).join('')||'<div class="empty">Заявок нет.</div>'}</div></div>`}catch(e){p.innerHTML=`<div class="panel"><b>${esc(e.message)}</b></div>`}}
async function verifyMaster(id,verified){try{await api('/api/masters/'+id,{method:'PATCH',body:JSON.stringify({verified})});renderAdminDashboard()}catch(e){alert(e.message)}}
$('#join').onclick=()=>{authModal();setTimeout(()=>{if($('#aRole'))$('#aRole').value='master'},50)};
me();
