const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),url=require('url');
const PORT=process.env.PORT||3000,HOST=process.env.HOST||'0.0.0.0';
const DATA=path.join(__dirname,'data.json'),PUBLIC=path.join(__dirname,'public'),UPLOADS=path.join(__dirname,'uploads');
if(!fs.existsSync(UPLOADS))fs.mkdirSync(UPLOADS,{recursive:true});
const CITIES={
  'Калининград':[54.7104,20.4522],'Гурьевск':[54.7714,20.6030],'Зеленоградск':[54.9599,20.4757],
  'Светлогорск':[54.9430,20.1531],'Пионерский':[54.9517,20.2276],'Балтийск':[54.6514,19.9071],
  'Черняховск':[54.6334,21.8156],'Советск':[55.0810,21.8883],'Гусев':[54.5922,22.1947]
};
function distanceKm(a,b){const A=CITIES[a]||CITIES['Калининград'],B=CITIES[b]||CITIES['Калининград'];const r=6371,la=(B[0]-A[0])*Math.PI/180,lo=(B[1]-A[1])*Math.PI/180,x=Math.sin(la/2)**2+Math.cos(A[0]*Math.PI/180)*Math.cos(B[0]*Math.PI/180)*Math.sin(lo/2)**2;return Math.round(2*r*Math.asin(Math.sqrt(x))*10)/10}

const seed={users:[],requests:[],messages:[],reviews:[]};
if(!fs.existsSync(DATA))fs.writeFileSync(DATA,JSON.stringify(seed,null,2));
function bootstrapAdmin(){const d=db(); if(!d.users.some(x=>x.role==='admin')){const a=d.adminBootstrap||{phone:'79990000000',password:'admin123'}; const ph=hash(a.password); d.users.push({id:'admin_demo',role:'admin',name:'FixNow Admin',phone:a.phone,city:'Калининград',category:'',rating:0,verified:true,passwordHash:ph.hash,passwordSalt:ph.salt,createdAt:new Date().toISOString()}); delete d.adminBootstrap; save(d)}}
bootstrapAdmin();
function db(){return JSON.parse(fs.readFileSync(DATA,'utf8'))} function save(x){fs.writeFileSync(DATA,JSON.stringify(x,null,2))}
function id(p){return p+crypto.randomBytes(7).toString('hex')}
function hash(p,s=crypto.randomBytes(16).toString('hex')){return {salt:s,hash:crypto.scryptSync(p,s,64).toString('hex')}}
function json(res,code,obj){res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,PATCH,OPTIONS'});res.end(JSON.stringify(obj))}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>2e6)req.destroy()});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})})}
const sessions=new Map();
function classify(t){t=(t||'').toLowerCase();if(/вода|теч|кран|унитаз|раков|труба|слив|душ|смес/.test(t))return['Сантехника','🚰','от 1 500 ₽'];if(/свет|розет|электр|провод|автомат|искр|выключател|ламп|напряж/.test(t))return['Электрика','⚡','от 1 500 ₽'];if(/двер|замок|ключ|личин|ручк/.test(t))return['Замки и двери','🔐','от 1 500 ₽'];if(/батаре|радиатор|отоп|кот[её]л|тепл|холодно/.test(t))return['Отопление','🔥','от 2 000 ₽'];if(/стирал|холодиль|посудомо|плит|духов|техник/.test(t))return['Бытовая техника','🧰','от 1 500 ₽'];return['Мастер на час','🛠️','от 1 000 ₽']}
function auth(req){const h=req.headers.authorization||'';const token=h.startsWith('Bearer ')?h.slice(7):'';const uid=sessions.get(token);if(!uid)return null;return db().users.find(x=>x.id===uid)||null}
function safeUser(u){if(!u)return null;const {passwordHash,passwordSalt,...x}=u;return x}
function staticFile(res,p){let f=!p||p==='/'?path.join(PUBLIC,'index.html'):path.join(PUBLIC,p);if(!fs.existsSync(f))return json(res,404,{error:'Not found'});const ext=path.extname(f),ct={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'application/javascript','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.webmanifest':'application/manifest+json','.svg':'image/svg+xml'}[ext]||'application/octet-stream';res.writeHead(200,{'Content-Type':ct});res.end(fs.readFileSync(f))}
async function api(req,res){const u=url.parse(req.url,true),dbx=db(),p=u.pathname;
if(req.method==='GET'&&p==='/api/health')return json(res,200,{ok:true,service:'FixNow',time:new Date().toISOString()});
if(req.method==='POST'&&p==='/api/register'){const b=await body(req),name=(b.name||'').trim(),phone=(b.phone||'').trim(),password=b.password||'',role=b.role==='master'?'master':'client',city=b.city||'Калининград',category=b.category||'';if(name.length<2||password.length<6)return json(res,400,{error:'Имя и пароль (минимум 6 символов) обязательны'});if(dbx.users.some(x=>x.phone===phone&&phone))return json(res,409,{error:'Пользователь с таким телефоном уже зарегистрирован'});const ph=hash(password);const user={id:id(role==='master'?'m_':'u_'),role,name,phone,city,category,rating:0,verified:role==='client',passwordHash:ph.hash,passwordSalt:ph.salt,createdAt:new Date().toISOString()};dbx.users.push(user);save(dbx);const token=id('sess_');sessions.set(token,user.id);return json(res,201,{token,user:safeUser(user)})}
if(req.method==='POST'&&p==='/api/login'){const b=await body(req),u=dbx.users.find(x=>x.phone===b.phone);if(!u||!u.passwordHash||crypto.scryptSync(b.password||'',u.passwordSalt,64).toString('hex')!==u.passwordHash)return json(res,401,{error:'Неверный телефон или пароль'});const token=id('sess_');sessions.set(token,u.id);return json(res,200,{token,user:safeUser(u)})}
if(req.method==='GET'&&p==='/api/me'){const sid=auth(req);if(!sid)return json(res,401,{error:'Не авторизован'});return json(res,200,{user:safeUser(dbx.users.find(x=>x.id===sid))})}
if(req.method==='POST'&&p==='/api/logout'){const t=(req.headers.authorization||'').replace('Bearer ','');sessions.delete(t);return json(res,200,{ok:true})}
if(req.method==='GET'&&p==='/api/masters'){const city=u.query.city||'';const cat=u.query.category;const radius=Math.max(0,Number(u.query.radius)||30);const a=dbx.users.filter(x=>x.role==='master'&&x.verified&&(!cat||x.category===cat)).map(x=>({...safeUser(x),distanceKm:distanceKm(city,x.city)})).filter(x=>!city||x.distanceKm<=radius).sort((a,b)=>a.distanceKm-b.distanceKm);return json(res,200,a)}
if(req.method==='GET'&&p==='/api/requests'){const me=auth(req);if(!me)return json(res,401,{error:'Нужен вход'});let a;if(me.role==='admin')a=dbx.requests;else if(me.role==='master')a=dbx.requests.filter(x=>x.masterId===me.id);else a=dbx.requests.filter(x=>x.clientId===me);return json(res,200,a)}
if(req.method==='GET'&&p==='/api/messages'){const me=auth(req);if(!me)return json(res,401,{error:'Нужен вход'});const rid=u.query.requestId;const q=dbx.requests.find(x=>x.id===rid);if(!q)return json(res,404,{error:'Заявка не найдена'});if(me.role!=='admin'&&q.clientId!==me&&q.masterId!==me)return json(res,403,{error:'Нет доступа'});return json(res,200,dbx.messages.filter(x=>x.requestId===rid))}
if(req.method==='GET'&&p==='/api/analyze')return json(res,405,{error:'POST required'});
if(req.method==='POST'&&p==='/api/analyze'){let b=await body(req),r=classify(b.text);return json(res,200,{category:r[0],icon:r[1],price:r[2],summary:`Предварительно определено направление «${r[0]}». Итоговую стоимость подтверждает мастер после уточнения задачи.`})}
if(req.method==='POST'&&p==='/api/uploads'){const me=auth(req);if(!me)return json(res,401,{error:'Нужен вход'});let b=await body(req),m=/^data:image\/(jpeg|png|webp);base64,([A-Za-z0-9+/=]+)$/.exec(b.dataUrl||'');if(!m)return json(res,400,{error:'Поддерживаются JPG, PNG и WEBP'});const raw=Buffer.from(m[2],'base64');if(raw.length>1.5e6)return json(res,413,{error:'Фото должно быть меньше 1.5 МБ'});const ext=m[1]==='jpeg'?'jpg':m[1],name=id('photo_')+'.'+ext;fs.writeFileSync(path.join(UPLOADS,name),raw);return json(res,201,{url:'/uploads/'+name})}
if(req.method==='POST'&&p==='/api/requests'){const me=auth(req);if(!me)return json(res,401,{error:'Сначала войдите в аккаунт'});if(me.role!=='client')return json(res,403,{error:'Заявки создают клиенты'});let b=await body(req),r=classify(b.problem),master=b.masterId?dbx.users.find(x=>x.id===b.masterId&&x.role==='master'&&x.verified):null;if(b.masterId&&!master)return json(res,400,{error:'Выбранный мастер недоступен'});let q={id:id('r_'),createdAt:new Date().toISOString(),status:'new',clientId:me.id,clientName:me.name,phone:me.phone,city:b.city||me.city,urgency:b.urgency||'Сегодня',problem:b.problem,category:r[0],price:r[2],masterId:b.masterId||null,photoUrl:b.photoUrl||null};dbx.requests.unshift(q);save(dbx);return json(res,201,q)}
if(req.method==='PATCH'&&p.startsWith('/api/requests/')){const me=auth(req);if(!me)return json(res,401,{error:'Нужен вход'});const rid=p.split('/').pop(),b=await body(req),q=dbx.requests.find(x=>x.id===rid);if(!q)return json(res,404,{error:'Заявка не найдена'});if(me.role==='client'&&q.clientId!==me.id)return json(res,403,{error:'Нет доступа'});if(me.role==='master'&&q.masterId!==me.id)return json(res,403,{error:'Нет доступа'});Object.assign(q,b,{updatedAt:new Date().toISOString()});save(dbx);return json(res,200,q)}
if(req.method==='POST'&&p==='/api/messages'){const me=auth(req);if(!me)return json(res,401,{error:'Нужен вход'});let b=await body(req),q=dbx.requests.find(x=>x.id===b.requestId);if(!q)return json(res,404,{error:'Заявка не найдена'});if(me.role!=='admin'&&q.clientId!==me.id&&q.masterId!==me.id)return json(res,403,{error:'Нет доступа'});let m={id:id('msg_'),createdAt:new Date().toISOString(),requestId:q.id,senderId:me.id,sender:me.role,text:(b.text||'').trim()};if(!m.text)return json(res,400,{error:'Пустое сообщение'});dbx.messages.push(m);save(dbx);return json(res,201,m)}
if(req.method==='POST'&&p==='/api/reviews'){const me=auth(req);if(!me||me.role!=='client')return json(res,403,{error:'Только клиент может оставить отзыв'});let b=await body(req),q=dbx.requests.find(x=>x.id===b.requestId);if(!q||q.clientId!==me.id||q.status!=='done')return json(res,400,{error:'Отзыв можно оставить после завершения заявки'});if(dbx.reviews.some(x=>x.requestId===q.id))return json(res,409,{error:'Отзыв уже оставлен'});let rating=Math.max(1,Math.min(5,Number(b.rating)||5));dbx.reviews.push({id:id('rev_'),requestId:q.id,masterId:q.masterId,rating,text:b.text||'',createdAt:new Date().toISOString()});save(dbx);return json(res,201,{ok:true})}
if(req.method==='GET'&&p==='/api/admin'){const me=auth(req);if(!me||me.role!=='admin')return json(res,403,{error:'Только администратор'});return json(res,200,{users:dbx.users.map(safeUser),requests:dbx.requests,messages:dbx.messages,reviews:dbx.reviews})}
if(req.method==='PATCH'&&p.startsWith('/api/masters/')){const me=auth(req);if(!me||me.role!=='admin')return json(res,403,{error:'Только администратор'});let b=await body(req),m=dbx.users.find(x=>x.id===p.split('/').pop()&&x.role==='master');if(!m)return json(res,404,{error:'Мастер не найден'});Object.assign(m,b);save(dbx);return json(res,200,safeUser(m))}
if(p.startsWith('/uploads/')){const f=path.join(UPLOADS,path.basename(p));if(!fs.existsSync(f))return json(res,404,{error:'Файл не найден'});const ext=path.extname(f),ct={'.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.webmanifest':'application/manifest+json','.svg':'image/svg+xml'}[ext]||'application/octet-stream';res.writeHead(200,{'Content-Type':ct});return res.end(fs.readFileSync(f))}
return staticFile(res,p)}
const server=http.createServer((req,res)=>{if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization'});return res.end()}api(req,res).catch(e=>json(res,500,{error:e.message}))});
server.listen(PORT,HOST,()=>console.log(`FixNow running: http://localhost:${PORT}`));
